export const DECK = [
  {
    id: "fondue",
    clues: [
      "swiss",
      "dish",
      "where",
      "food",
      "involves",
      "submerging",
      "in",
      "melted",
      "cheese",
      "pot",
    ],
    answer: "Fondue",
    aliases: ["cheese fondue"],
  },
  {
    id: "pizza",
    clues: [
      "italian",
      "round",
      "flat",
      "bread",
      "topped",
      "with",
      "tomato",
      "cheese",
      "and",
      "toppings",
    ],
    answer: "Pizza",
    aliases: [],
  },
  {
    id: "sushi",
    clues: ["japanese", "dish", "of", "raw", "fish", "served", "on", "vinegared", "rice", "rolls"],
    answer: "Sushi",
    aliases: [],
  },
  {
    id: "tacos",
    clues: [
      "mexican",
      "folded",
      "corn",
      "shells",
      "filled",
      "with",
      "meat",
      "salsa",
      "and",
      "cheese",
    ],
    answer: "Tacos",
    aliases: ["taco"],
  },
  {
    id: "bicycle",
    clues: [
      "two",
      "wheeled",
      "vehicle",
      "powered",
      "by",
      "human",
      "legs",
      "pushing",
      "the",
      "pedals",
    ],
    answer: "Bicycle",
    aliases: ["bike"],
  },
  {
    id: "skateboard",
    clues: [
      "wooden",
      "board",
      "with",
      "four",
      "wheels",
      "ridden",
      "while",
      "standing",
      "and",
      "balancing",
    ],
    answer: "Skateboard",
    aliases: [],
  },
  {
    id: "umbrella",
    clues: [
      "folding",
      "fabric",
      "canopy",
      "carried",
      "to",
      "shield",
      "person",
      "from",
      "rain",
      "above",
    ],
    answer: "Umbrella",
    aliases: [],
  },
  {
    id: "telescope",
    clues: [
      "long",
      "tube",
      "with",
      "lenses",
      "used",
      "for",
      "viewing",
      "distant",
      "stars",
      "magnified",
    ],
    answer: "Telescope",
    aliases: [],
  },
  {
    id: "rainbow",
    clues: ["colorful", "arc", "in", "the", "sky", "appearing", "after", "rain", "and", "sunshine"],
    answer: "Rainbow",
    aliases: [],
  },
  {
    id: "volcano",
    clues: ["mountain", "that", "erupts", "with", "molten", "lava", "ash", "and", "hot", "gases"],
    answer: "Volcano",
    aliases: [],
  },
  {
    id: "pyramid",
    clues: [
      "ancient",
      "stone",
      "monument",
      "with",
      "four",
      "triangular",
      "sides",
      "built",
      "in",
      "egypt",
    ],
    answer: "Pyramid",
    aliases: ["pyramids"],
  },
  {
    id: "lighthouse",
    clues: [
      "tall",
      "coastal",
      "tower",
      "shining",
      "a",
      "bright",
      "beam",
      "warning",
      "passing",
      "ships",
    ],
    answer: "Lighthouse",
    aliases: [],
  },
  {
    id: "helicopter",
    clues: [
      "aircraft",
      "lifted",
      "by",
      "spinning",
      "rotor",
      "blades",
      "above",
      "the",
      "pilot",
      "cabin",
    ],
    answer: "Helicopter",
    aliases: ["chopper"],
  },
  {
    id: "submarine",
    clues: [
      "underwater",
      "naval",
      "vessel",
      "designed",
      "for",
      "stealthy",
      "travel",
      "beneath",
      "the",
      "ocean",
    ],
    answer: "Submarine",
    aliases: ["sub"],
  },
  {
    id: "lasagna",
    clues: [
      "layered",
      "italian",
      "pasta",
      "dish",
      "with",
      "meat",
      "tomato",
      "sauce",
      "and",
      "cheese",
    ],
    answer: "Lasagna",
    aliases: ["lasagne"],
  },
  {
    id: "library",
    clues: [
      "public",
      "building",
      "filled",
      "with",
      "books",
      "available",
      "to",
      "borrow",
      "and",
      "read",
    ],
    answer: "Library",
    aliases: [],
  },
  {
    id: "dentist",
    clues: [
      "medical",
      "professional",
      "who",
      "examines",
      "cleans",
      "and",
      "repairs",
      "your",
      "teeth",
      "regularly",
    ],
    answer: "Dentist",
    aliases: [],
  },
  {
    id: "astronaut",
    clues: ["person", "trained", "to", "travel", "and", "work", "in", "outer", "space", "missions"],
    answer: "Astronaut",
    aliases: ["cosmonaut"],
  },
  {
    id: "penguin",
    clues: [
      "flightless",
      "black",
      "and",
      "white",
      "bird",
      "that",
      "waddles",
      "and",
      "swims",
      "expertly",
    ],
    answer: "Penguin",
    aliases: [],
  },
  {
    id: "octopus",
    clues: [
      "sea",
      "creature",
      "with",
      "eight",
      "arms",
      "and",
      "the",
      "ability",
      "to",
      "camouflage",
    ],
    answer: "Octopus",
    aliases: [],
  },
  {
    id: "kangaroo",
    clues: [
      "australian",
      "marsupial",
      "that",
      "hops",
      "on",
      "powerful",
      "legs",
      "carrying",
      "young",
      "joeys",
    ],
    answer: "Kangaroo",
    aliases: [],
  },
  {
    id: "origami",
    clues: [
      "japanese",
      "art",
      "of",
      "folding",
      "paper",
      "into",
      "decorative",
      "shapes",
      "without",
      "cutting",
    ],
    answer: "Origami",
    aliases: [],
  },
  {
    id: "jigsaw",
    clues: [
      "puzzle",
      "of",
      "interlocking",
      "pieces",
      "assembled",
      "to",
      "complete",
      "a",
      "single",
      "picture",
    ],
    answer: "Jigsaw puzzle",
    aliases: ["jigsaw", "puzzle"],
  },
  {
    id: "karaoke",
    clues: [
      "singing",
      "popular",
      "songs",
      "into",
      "a",
      "microphone",
      "while",
      "lyrics",
      "scroll",
      "onscreen",
    ],
    answer: "Karaoke",
    aliases: [],
  },
  {
    id: "marathon",
    clues: [
      "long",
      "distance",
      "running",
      "race",
      "covering",
      "twenty",
      "six",
      "point",
      "two",
      "miles",
    ],
    answer: "Marathon",
    aliases: [],
  },
  {
    id: "snowman",
    clues: [
      "winter",
      "figure",
      "built",
      "from",
      "stacked",
      "snowballs",
      "with",
      "carrot",
      "nose",
      "added",
    ],
    answer: "Snowman",
    aliases: [],
  },
  {
    id: "treasure-chest",
    clues: [
      "wooden",
      "box",
      "filled",
      "with",
      "gold",
      "coins",
      "and",
      "jewels",
      "buried",
      "underground",
    ],
    answer: "Treasure chest",
    aliases: ["treasure", "chest"],
  },
  {
    id: "guitar",
    clues: [
      "stringed",
      "instrument",
      "with",
      "fretted",
      "neck",
      "played",
      "by",
      "strumming",
      "or",
      "picking",
    ],
    answer: "Guitar",
    aliases: [],
  },
  {
    id: "elevator",
    clues: [
      "vertical",
      "moving",
      "room",
      "carrying",
      "people",
      "between",
      "floors",
      "of",
      "tall",
      "buildings",
    ],
    answer: "Elevator",
    aliases: ["lift"],
  },
  {
    id: "hammock",
    clues: [
      "fabric",
      "sling",
      "suspended",
      "between",
      "two",
      "trees",
      "for",
      "lazy",
      "outdoor",
      "napping",
    ],
    answer: "Hammock",
    aliases: [],
  },
];
